### ISSUE TITLE
Animation adds extra line above px-progress-bar

### ISSUE THREAD

**Issue by connie-ru-wang** [PredixDev/px-progress-bar#1]
With a Chrome browser window height greater than 1200 with animation enabled on the progress bar, a line gets added above the progress bar. If the browser window is smaller then the line disappears and if the animation is removed then the line disappears. The line also does not appear in Firefox.
![screen shot 2016-12-09 at 3 01 35 pm](https://cloud.githubusercontent.com/assets/6410318/21067509/6b59f326-be20-11e6-9196-779bd264c54c.png)

**Comment by randyaskin** [comment]
I'm not able to replicate this at any browser resolution (my monitor is 2560x1440, browser in full screen) or any browser zoom level on Chrome 55. What operating system and version of Chrome are you using? Are you sure it's not being introduced in your application code somehow?

**Comment by randyaskin** [comment]
Closing this due to non-responsiveness. Reopen if this is still an issue.
