### ISSUE TITLE
Configurable Progress Bar

### ISSUE THREAD

**Issue by Aparna13** [PredixDev/px-progress-bar#4]
Progress bar with configurable:
Height
Background color
Progress bar color
<img width="1687" alt="screen shot 2017-10-04 at 1 16 12 pm" src="https://user-images.githubusercontent.com/10138396/31350343-aafc8ec6-acdb-11e7-9d8b-953c34a6ed6e.png">

**Comment by davidrleonard** [comment]
Turns out the style variables for these were already defined, they just weren't showing up on the docs site. I fixed that a few other small things in #5. Once that drops on a new tag we'll close this.

**Comment by davidrleonard** [comment]
Everything is set up, grab the latest px-progress-var at v1.1.0.
