### ISSUE TITLE
Support Polymer 2.0

### ISSUE THREAD

**Issue by shinxi** [PredixDev/px-progress-bar#6]
px-progress-bar doesn't work with polymer 2.0. Is there any plan on support polymer 2.X, @davidrleonard 

## Expected behavior and actual behavior:
px-progress-bar works as expected with polymer 2.0

## Steps to reproduce the problem:
https://codepen.io/anon/pen/VMOvzv?&editors=1001

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-progress-bar: ^1.1.0
polymer: 2.0.0
Browser: Google Chrome 61.0.3163.100
operating system: macOS Sierra 10.12.6

## Screenshots (_optional, but very helpful_):
![image](https://user-images.githubusercontent.com/1262296/31885075-e5fcb706-b7b4-11e7-901d-39f9162dc5cb.png)
There's no progress indicator at the progress bar.

## Code examples
https://codepen.io/anon/pen/VMOvzv?&editors=1001

**Comment by davidrleonard** [comment]
See the polymer2.0-preview branch. That branch is a pre-release with the progress bar working in Polymer 2.x. We will release it as a minor update when everything is hashed out. You can install that branch name directly in your bower.json file for now (`"px-progress-bar" : "polymer2.0-preview"`).
